// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc2
// source: proto/notes.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	GithubUsername      string                 `protobuf:"bytes,1,opt,name=github_username,json=githubUsername,proto3" json:"github_username,omitempty"`
	GithubOauthToken    string                 `protobuf:"bytes,2,opt,name=github_oauth_token,json=githubOauthToken,proto3" json:"github_oauth_token,omitempty"`
	GdriveOauthToken    string                 `protobuf:"bytes,3,opt,name=gdrive_oauth_token,json=gdriveOauthToken,proto3" json:"gdrive_oauth_token,omitempty"`
	GdriveRefreshToken  string                 `protobuf:"bytes,4,opt,name=gdrive_refresh_token,json=gdriveRefreshToken,proto3" json:"gdrive_refresh_token,omitempty"`
	GdriveTokenExpiry   int64                  `protobuf:"varint,5,opt,name=gdrive_token_expiry,json=gdriveTokenExpiry,proto3" json:"gdrive_token_expiry,omitempty"`
	GdriveNotesFolderId string                 `protobuf:"bytes,6,opt,name=gdrive_notes_folder_id,json=gdriveNotesFolderId,proto3" json:"gdrive_notes_folder_id,omitempty"`
	LastSyncTime        int64                  `protobuf:"varint,7,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserConfig) Reset() {
	*x = UserConfig{}
	mi := &file_proto_notes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConfig) ProtoMessage() {}

func (x *UserConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConfig.ProtoReflect.Descriptor instead.
func (*UserConfig) Descriptor() ([]byte, []int) {
	return file_proto_notes_proto_rawDescGZIP(), []int{0}
}

func (x *UserConfig) GetGithubUsername() string {
	if x != nil {
		return x.GithubUsername
	}
	return ""
}

func (x *UserConfig) GetGithubOauthToken() string {
	if x != nil {
		return x.GithubOauthToken
	}
	return ""
}

func (x *UserConfig) GetGdriveOauthToken() string {
	if x != nil {
		return x.GdriveOauthToken
	}
	return ""
}

func (x *UserConfig) GetGdriveRefreshToken() string {
	if x != nil {
		return x.GdriveRefreshToken
	}
	return ""
}

func (x *UserConfig) GetGdriveTokenExpiry() int64 {
	if x != nil {
		return x.GdriveTokenExpiry
	}
	return 0
}

func (x *UserConfig) GetGdriveNotesFolderId() string {
	if x != nil {
		return x.GdriveNotesFolderId
	}
	return ""
}

func (x *UserConfig) GetLastSyncTime() int64 {
	if x != nil {
		return x.LastSyncTime
	}
	return 0
}

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PageNumber    int32                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	DriveFileId   string                 `protobuf:"bytes,3,opt,name=drive_file_id,json=driveFileId,proto3" json:"drive_file_id,omitempty"`
	GithubProject string                 `protobuf:"bytes,4,opt,name=github_project,json=githubProject,proto3" json:"github_project,omitempty"` // Format: "owner/repo"
	Processed     bool                   `protobuf:"varint,5,opt,name=processed,proto3" json:"processed,omitempty"`
	CreatedTime   int64                  `protobuf:"varint,6,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime   int64                  `protobuf:"varint,7,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	LocalFilePath string                 `protobuf:"bytes,8,opt,name=local_file_path,json=localFilePath,proto3" json:"local_file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_proto_notes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_proto_notes_proto_rawDescGZIP(), []int{1}
}

func (x *Page) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Page) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *Page) GetDriveFileId() string {
	if x != nil {
		return x.DriveFileId
	}
	return ""
}

func (x *Page) GetGithubProject() string {
	if x != nil {
		return x.GithubProject
	}
	return ""
}

func (x *Page) GetProcessed() bool {
	if x != nil {
		return x.Processed
	}
	return false
}

func (x *Page) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *Page) GetUpdatedTime() int64 {
	if x != nil {
		return x.UpdatedTime
	}
	return 0
}

func (x *Page) GetLocalFilePath() string {
	if x != nil {
		return x.LocalFilePath
	}
	return ""
}

type Notebook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DriveFolderId string                 `protobuf:"bytes,3,opt,name=drive_folder_id,json=driveFolderId,proto3" json:"drive_folder_id,omitempty"`
	GithubProject string                 `protobuf:"bytes,4,opt,name=github_project,json=githubProject,proto3" json:"github_project,omitempty"` // Format: "owner/repo"
	Pages         []*Page                `protobuf:"bytes,5,rep,name=pages,proto3" json:"pages,omitempty"`
	LastUpdated   int64                  `protobuf:"varint,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notebook) Reset() {
	*x = Notebook{}
	mi := &file_proto_notes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notebook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notebook) ProtoMessage() {}

func (x *Notebook) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notebook.ProtoReflect.Descriptor instead.
func (*Notebook) Descriptor() ([]byte, []int) {
	return file_proto_notes_proto_rawDescGZIP(), []int{2}
}

func (x *Notebook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notebook) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notebook) GetDriveFolderId() string {
	if x != nil {
		return x.DriveFolderId
	}
	return ""
}

func (x *Notebook) GetGithubProject() string {
	if x != nil {
		return x.GithubProject
	}
	return ""
}

func (x *Notebook) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *Notebook) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

var File_proto_notes_proto protoreflect.FileDescriptor

const file_proto_notes_proto_rawDesc = "" +
	"\n" +
	"\x11proto/notes.proto\x12\x05notes\"\xce\x02\n" +
	"\n" +
	"UserConfig\x12'\n" +
	"\x0fgithub_username\x18\x01 \x01(\tR\x0egithubUsername\x12,\n" +
	"\x12github_oauth_token\x18\x02 \x01(\tR\x10githubOauthToken\x12,\n" +
	"\x12gdrive_oauth_token\x18\x03 \x01(\tR\x10gdriveOauthToken\x120\n" +
	"\x14gdrive_refresh_token\x18\x04 \x01(\tR\x12gdriveRefreshToken\x12.\n" +
	"\x13gdrive_token_expiry\x18\x05 \x01(\x03R\x11gdriveTokenExpiry\x123\n" +
	"\x16gdrive_notes_folder_id\x18\x06 \x01(\tR\x13gdriveNotesFolderId\x12$\n" +
	"\x0elast_sync_time\x18\a \x01(\x03R\flastSyncTime\"\x8e\x02\n" +
	"\x04Page\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12\"\n" +
	"\rdrive_file_id\x18\x03 \x01(\tR\vdriveFileId\x12%\n" +
	"\x0egithub_project\x18\x04 \x01(\tR\rgithubProject\x12\x1c\n" +
	"\tprocessed\x18\x05 \x01(\bR\tprocessed\x12!\n" +
	"\fcreated_time\x18\x06 \x01(\x03R\vcreatedTime\x12!\n" +
	"\fupdated_time\x18\a \x01(\x03R\vupdatedTime\x12&\n" +
	"\x0flocal_file_path\x18\b \x01(\tR\rlocalFilePath\"\xc5\x01\n" +
	"\bNotebook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12&\n" +
	"\x0fdrive_folder_id\x18\x03 \x01(\tR\rdriveFolderId\x12%\n" +
	"\x0egithub_project\x18\x04 \x01(\tR\rgithubProject\x12!\n" +
	"\x05pages\x18\x05 \x03(\v2\v.notes.PageR\x05pages\x12!\n" +
	"\flast_updated\x18\x06 \x01(\x03R\vlastUpdatedB%Z#github.com/brotherlogic/notes/protob\x06proto3"

var (
	file_proto_notes_proto_rawDescOnce sync.Once
	file_proto_notes_proto_rawDescData []byte
)

func file_proto_notes_proto_rawDescGZIP() []byte {
	file_proto_notes_proto_rawDescOnce.Do(func() {
		file_proto_notes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notes_proto_rawDesc), len(file_proto_notes_proto_rawDesc)))
	})
	return file_proto_notes_proto_rawDescData
}

var file_proto_notes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_notes_proto_goTypes = []any{
	(*UserConfig)(nil), // 0: notes.UserConfig
	(*Page)(nil),       // 1: notes.Page
	(*Notebook)(nil),   // 2: notes.Notebook
}
var file_proto_notes_proto_depIdxs = []int32{
	1, // 0: notes.Notebook.pages:type_name -> notes.Page
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_notes_proto_init() }
func file_proto_notes_proto_init() {
	if File_proto_notes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notes_proto_rawDesc), len(file_proto_notes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_notes_proto_goTypes,
		DependencyIndexes: file_proto_notes_proto_depIdxs,
		MessageInfos:      file_proto_notes_proto_msgTypes,
	}.Build()
	File_proto_notes_proto = out.File
	file_proto_notes_proto_goTypes = nil
	file_proto_notes_proto_depIdxs = nil
}
